import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

let supabase: any;

console.log('Supabase URL:', supabaseUrl ? 'Present' : 'Missing');
console.log('Supabase Anon Key:', supabaseAnonKey ? 'Present' : 'Missing');

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Supabase environment variables are missing!');
  console.error('Please ensure your .env file contains:');
  console.error('EXPO_PUBLIC_SUPABASE_URL="your_supabase_url"');
  console.error('EXPO_PUBLIC_SUPABASE_ANON_KEY="your_supabase_anon_key"');
  throw new Error('Supabase configuration missing. Please check your .env file.');
}

try {
  supabase = createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false,
    },
  });
  console.log('✅ Supabase client initialized successfully');
} catch (error) {
  console.error('❌ Failed to initialize Supabase client:', error);
  throw error;
}

export { supabase };

export type Database = {
  public: {
    Tables: {
      posts: {
        Row: {
          id: string;
          author_id: string | null;
          author_name: string;
          author_username: string;
          author_avatar_url: string;
          author_verified: boolean;
          author_role: string;
          caption: string;
          post_type: 'text' | 'image' | 'video' | 'carousel' | 'poll' | 'event';
          content_data: any;
          likes_count: number;
          comments_count: number;
          shares_count: number;
          views_count: number;
          saves_count: number;
          status: 'draft' | 'published' | 'archived' | 'deleted' | 'scheduled';
          visibility: 'public' | 'followers' | 'private';
          scheduled_for: string | null;
          published_at: string;
          tags: string[];
          category: string;
          target_audience: string[];
          location: string;
          engagement_score: number;
          trending_score: number;
          quality_score: number;
          is_featured: boolean;
          is_pinned: boolean;
          content_warnings: string[];
          moderation_status: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_id?: string | null;
          author_name?: string;
          author_username?: string;
          author_avatar_url?: string;
          author_verified?: boolean;
          author_role?: string;
          caption: string;
          post_type?: 'text' | 'image' | 'video' | 'carousel' | 'poll' | 'event';
          content_data?: any;
          likes_count?: number;
          comments_count?: number;
          shares_count?: number;
          views_count?: number;
          saves_count?: number;
          status?: 'draft' | 'published' | 'archived' | 'deleted' | 'scheduled';
          visibility?: 'public' | 'followers' | 'private';
          scheduled_for?: string | null;
          published_at?: string;
          tags?: string[];
          category?: string;
          target_audience?: string[];
          location?: string;
          engagement_score?: number;
          trending_score?: number;
          quality_score?: number;
          is_featured?: boolean;
          is_pinned?: boolean;
          content_warnings?: string[];
          moderation_status?: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_id?: string | null;
          author_name?: string;
          author_username?: string;
          author_avatar_url?: string;
          author_verified?: boolean;
          author_role?: string;
          caption?: string;
          post_type?: 'text' | 'image' | 'video' | 'carousel' | 'poll' | 'event';
          content_data?: any;
          likes_count?: number;
          comments_count?: number;
          shares_count?: number;
          views_count?: number;
          saves_count?: number;
          status?: 'draft' | 'published' | 'archived' | 'deleted' | 'scheduled';
          visibility?: 'public' | 'followers' | 'private';
          scheduled_for?: string | null;
          published_at?: string;
          tags?: string[];
          category?: string;
          target_audience?: string[];
          location?: string;
          engagement_score?: number;
          trending_score?: number;
          quality_score?: number;
          is_featured?: boolean;
          is_pinned?: boolean;
          content_warnings?: string[];
          moderation_status?: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at?: string;
          updated_at?: string;
        };
      };
      post_media: {
        Row: {
          id: string;
          post_id: string;
          media_type: 'image' | 'video' | 'gif' | 'audio';
          media_url: string;
          thumbnail_url: string | null;
          alt_text: string;
          file_size: number | null;
          duration: number | null;
          width: number | null;
          height: number | null;
          format: string | null;
          order_index: number;
          is_primary: boolean;
          processing_status: 'pending' | 'processing' | 'completed' | 'failed';
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          media_type: 'image' | 'video' | 'gif' | 'audio';
          media_url: string;
          thumbnail_url?: string | null;
          alt_text?: string;
          file_size?: number | null;
          duration?: number | null;
          width?: number | null;
          height?: number | null;
          format?: string | null;
          order_index?: number;
          is_primary?: boolean;
          processing_status?: 'pending' | 'processing' | 'completed' | 'failed';
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          media_type?: 'image' | 'video' | 'gif' | 'audio';
          media_url?: string;
          thumbnail_url?: string | null;
          alt_text?: string;
          file_size?: number | null;
          duration?: number | null;
          width?: number | null;
          height?: number | null;
          format?: string | null;
          order_index?: number;
          is_primary?: boolean;
          processing_status?: 'pending' | 'processing' | 'completed' | 'failed';
          created_at?: string;
        };
      };
      post_interactions: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          interaction_type: 'like' | 'share' | 'save' | 'view' | 'click' | 'report';
          interaction_data: any;
          device_info: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          interaction_type: 'like' | 'share' | 'save' | 'view' | 'click' | 'report';
          interaction_data?: any;
          device_info?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          interaction_type?: 'like' | 'share' | 'save' | 'view' | 'click' | 'report';
          interaction_data?: any;
          device_info?: any;
          created_at?: string;
        };
      };
      post_comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          parent_comment_id: string | null;
          content: string;
          likes_count: number;
          replies_count: number;
          is_edited: boolean;
          is_pinned: boolean;
          moderation_status: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          parent_comment_id?: string | null;
          content: string;
          likes_count?: number;
          replies_count?: number;
          is_edited?: boolean;
          is_pinned?: boolean;
          moderation_status?: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          parent_comment_id?: string | null;
          content?: string;
          likes_count?: number;
          replies_count?: number;
          is_edited?: boolean;
          is_pinned?: boolean;
          moderation_status?: 'pending' | 'approved' | 'rejected' | 'flagged';
          created_at?: string;
          updated_at?: string;
        };
      };
      post_hashtags: {
        Row: {
          id: string;
          hashtag: string;
          usage_count: number;
          trending_score: number;
          category: string;
          first_used_at: string;
          last_used_at: string;
        };
        Insert: {
          id?: string;
          hashtag: string;
          usage_count?: number;
          trending_score?: number;
          category?: string;
          first_used_at?: string;
          last_used_at?: string;
        };
        Update: {
          id?: string;
          hashtag?: string;
          usage_count?: number;
          trending_score?: number;
          category?: string;
          first_used_at?: string;
          last_used_at?: string;
        };
      };
      user_saved_posts: {
        Row: {
          id: string;
          user_id: string;
          post_id: string;
          collection_name: string;
          notes: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          post_id: string;
          collection_name?: string;
          notes?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          post_id?: string;
          collection_name?: string;
          notes?: string;
          created_at?: string;
        };
      };
      aptitude_questions: {
        Row: {
          id: string;
          question: string;
          options: string[];
          correct_answer: number;
          category: string;
          difficulty: string;
          explanation: string;
          time_limit: number;
          order_index: number;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          question: string;
          options: string[];
          correct_answer: number;
          category?: string;
          difficulty?: string;
          explanation?: string;
          time_limit?: number;
          order_index?: number;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          question?: string;
          options?: string[];
          correct_answer?: number;
          category?: string;
          difficulty?: string;
          explanation?: string;
          time_limit?: number;
          order_index?: number;
          active?: boolean;
          created_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          profile_photo_url: string;
          bio: string;
          interests: any[];
          projects: any[];
          education_level: string;
          field_of_study: string;
          graduation_year: number | null;
          location: string;
          website_url: string;
          linkedin_url: string;
          github_url: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name?: string;
          profile_photo_url?: string;
          bio?: string;
          interests?: any[];
          projects?: any[];
          education_level?: string;
          field_of_study?: string;
          graduation_year?: number | null;
          location?: string;
          website_url?: string;
          linkedin_url?: string;
          github_url?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          profile_photo_url?: string;
          bio?: string;
          interests?: any[];
          projects?: any[];
          education_level?: string;
          field_of_study?: string;
          graduation_year?: number | null;
          location?: string;
          website_url?: string;
          linkedin_url?: string;
          github_url?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          theme: string;
          notifications_enabled: boolean;
          email_notifications: boolean;
          push_notifications: boolean;
          privacy_level: string;
          language: string;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          theme?: string;
          notifications_enabled?: boolean;
          email_notifications?: boolean;
          push_notifications?: boolean;
          privacy_level?: string;
          language?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          theme?: string;
          notifications_enabled?: boolean;
          email_notifications?: boolean;
          push_notifications?: boolean;
          privacy_level?: string;
          language?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string;
          category: string;
          tags: string[];
          is_favorite: boolean;
          is_private: boolean;
          color_theme: string;
          note_type: 'note' | 'journal' | 'idea' | 'task' | 'research';
          created_at: string;
          updated_at: string;
          word_count: number;
          reading_time: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          content: string;
          category?: string;
          tags?: string[];
          is_favorite?: boolean;
          is_private?: boolean;
          color_theme?: string;
          note_type?: 'note' | 'journal' | 'idea' | 'task' | 'research';
          created_at?: string;
          updated_at?: string;
          word_count?: number;
          reading_time?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          content?: string;
          category?: string;
          tags?: string[];
          is_favorite?: boolean;
          is_private?: boolean;
          color_theme?: string;
          note_type?: 'note' | 'journal' | 'idea' | 'task' | 'research';
          created_at?: string;
          updated_at?: string;
          word_count?: number;
          reading_time?: number;
        };
      };
    };
    schedule_events: {
      Row: {
        id: string;
        user_id: string;
        title: string;
        description: string;
        start_time: string;
        end_time: string;
        event_date: string;
        location: string;
        event_type: string;
        color: string;
        recurring: boolean;
        recurring_pattern: string;
        reminders: number[];
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        title: string;
        description?: string;
        start_time: string;
        end_time: string;
        event_date: string;
        location?: string;
        event_type?: string;
        color?: string;
        recurring?: boolean;
        recurring_pattern?: string;
        reminders?: number[];
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        title?: string;
        description?: string;
        start_time?: string;
        end_time?: string;
        event_date?: string;
        location?: string;
        event_type?: string;
        color?: string;
        recurring?: boolean;
        recurring_pattern?: string;
        reminders?: number[];
        created_at?: string;
        updated_at?: string;
      };
    };
    assignments: {
      Row: {
        id: string;
        user_id: string;
        title: string;
        description: string;
        subject: string;
        due_date: string;
        due_time: string;
        priority: 'low' | 'medium' | 'high' | 'urgent';
        status: 'pending' | 'in_progress' | 'completed' | 'overdue';
        estimated_hours: number;
        actual_hours: number | null;
        reminders: any[];
        attachments: string[];
        notes: string;
        notification_ids: string[];
        completed_at: string | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        title: string;
        description?: string;
        subject?: string;
        due_date: string;
        due_time: string;
        priority?: 'low' | 'medium' | 'high' | 'urgent';
        status?: 'pending' | 'in_progress' | 'completed' | 'overdue';
        estimated_hours?: number;
        actual_hours?: number | null;
        reminders?: any[];
        attachments?: string[];
        notes?: string;
        notification_ids?: string[];
        completed_at?: string | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        title?: string;
        description?: string;
        subject?: string;
        due_date?: string;
        due_time?: string;
        priority?: 'low' | 'medium' | 'high' | 'urgent';
        status?: 'pending' | 'in_progress' | 'completed' | 'overdue';
        estimated_hours?: number;
        actual_hours?: number | null;
        reminders?: any[];
        attachments?: string[];
        notes?: string;
        notification_ids?: string[];
        completed_at?: string | null;
        created_at?: string;
        updated_at?: string;
      };
    };
    study_plans: {
      Row: {
        id: string;
        user_id: string;
        plan_name: string;
        description: string;
        subject: string;
        target_date: string;
        status: 'active' | 'completed' | 'paused' | 'cancelled';
        priority: 'low' | 'medium' | 'high' | 'urgent';
        study_sessions: any[];
        goals: any[];
        progress_percentage: number;
        total_hours_planned: number;
        total_hours_completed: number;
        study_methods: any[];
        resources: any[];
        notes: string;
        reminder_settings: any;
        tags: any[];
        is_archived: boolean;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        plan_name: string;
        description?: string;
        subject?: string;
        target_date: string;
        status?: 'active' | 'completed' | 'paused' | 'cancelled';
        priority?: 'low' | 'medium' | 'high' | 'urgent';
        study_sessions?: any[];
        goals?: any[];
        progress_percentage?: number;
        total_hours_planned?: number;
        total_hours_completed?: number;
        study_methods?: any[];
        resources?: any[];
        notes?: string;
        reminder_settings?: any;
        tags?: any[];
        is_archived?: boolean;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        plan_name?: string;
        description?: string;
        subject?: string;
        target_date?: string;
        status?: 'active' | 'completed' | 'paused' | 'cancelled';
        priority?: 'low' | 'medium' | 'high' | 'urgent';
        study_sessions?: any[];
        goals?: any[];
        progress_percentage?: number;
        total_hours_planned?: number;
        total_hours_completed?: number;
        study_methods?: any[];
        resources?: any[];
        notes?: string;
        reminder_settings?: any;
        tags?: any[];
        is_archived?: boolean;
        created_at?: string;
        updated_at?: string;
      };
    };
    career_events: {
      Row: {
        id: string;
        user_id: string;
        title: string;
        event_type: 'job_fair' | 'networking' | 'workshop' | 'interview' | 'application_deadline' | 'conference' | 'webinar';
        description: string;
        event_date: string;
        event_time: string;
        location: string;
        organizer: string;
        website_url: string;
        contact_email: string;
        registration_required: boolean;
        registration_deadline: string | null;
        cost: string;
        capacity: string;
        skills_focus: string[];
        target_audience: string;
        benefits: string;
        preparation_tips: string;
        status: 'upcoming' | 'registered' | 'attended' | 'missed';
        reminder_set: boolean;
        notes: string;
        order_index: number;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        title: string;
        event_type?: 'job_fair' | 'networking' | 'workshop' | 'interview' | 'application_deadline' | 'conference' | 'webinar';
        description?: string;
        event_date: string;
        event_time?: string;
        location?: string;
        organizer?: string;
        website_url?: string;
        contact_email?: string;
        registration_required?: boolean;
        registration_deadline?: string | null;
        cost?: string;
        capacity?: string;
        skills_focus?: string[];
        target_audience?: string;
        benefits?: string;
        preparation_tips?: string;
        status?: 'upcoming' | 'registered' | 'attended' | 'missed';
        reminder_set?: boolean;
        notes?: string;
        order_index?: number;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        title?: string;
        event_type?: 'job_fair' | 'networking' | 'workshop' | 'interview' | 'application_deadline' | 'conference' | 'webinar';
        description?: string;
        event_date?: string;
        event_time?: string;
        location?: string;
        organizer?: string;
        website_url?: string;
        contact_email?: string;
        registration_required?: boolean;
        registration_deadline?: string | null;
        cost?: string;
        capacity?: string;
        skills_focus?: string[];
        target_audience?: string;
        benefits?: string;
        preparation_tips?: string;
        status?: 'upcoming' | 'registered' | 'attended' | 'missed';
        reminder_set?: boolean;
        notes?: string;
        order_index?: number;
        created_at?: string;
        updated_at?: string;
      };
    };
    career_goals: {
      Row: {
        id: string;
        user_id: string;
        goal_title: string;
        goal_type: 'short_term' | 'medium_term' | 'long_term';
        description: string;
        target_date: string;
        priority: 'low' | 'medium' | 'high' | 'critical';
        status: 'not_started' | 'in_progress' | 'completed' | 'on_hold';
        progress_percentage: number;
        milestones: any[];
        resources_needed: string[];
        skills_to_develop: string[];
        networking_targets: string[];
        action_steps: any[];
        success_metrics: string[];
        obstacles: string[];
        support_needed: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        goal_title: string;
        goal_type?: 'short_term' | 'medium_term' | 'long_term';
        description?: string;
        target_date: string;
        priority?: 'low' | 'medium' | 'high' | 'critical';
        status?: 'not_started' | 'in_progress' | 'completed' | 'on_hold';
        progress_percentage?: number;
        milestones?: any[];
        resources_needed?: string[];
        skills_to_develop?: string[];
        networking_targets?: string[];
        action_steps?: any[];
        success_metrics?: string[];
        obstacles?: string[];
        support_needed?: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        goal_title?: string;
        goal_type?: 'short_term' | 'medium_term' | 'long_term';
        description?: string;
        target_date?: string;
        priority?: 'low' | 'medium' | 'high' | 'critical';
        status?: 'not_started' | 'in_progress' | 'completed' | 'on_hold';
        progress_percentage?: number;
        milestones?: any[];
        resources_needed?: string[];
        skills_to_develop?: string[];
        networking_targets?: string[];
        action_steps?: any[];
        success_metrics?: string[];
        obstacles?: string[];
        support_needed?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    job_applications: {
      Row: {
        id: string;
        user_id: string;
        company_name: string;
        position_title: string;
        application_date: string;
        application_status: 'applied' | 'screening' | 'interview' | 'offer' | 'rejected' | 'withdrawn';
        job_description: string;
        salary_range: string;
        location: string;
        application_url: string;
        contact_person: string;
        contact_email: string;
        interview_dates: string[];
        follow_up_dates: string[];
        notes: string;
        skills_required: string[];
        company_research: string;
        application_materials: string[];
        next_steps: string;
        priority_level: 'low' | 'medium' | 'high';
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        company_name: string;
        position_title: string;
        application_date: string;
        application_status?: 'applied' | 'screening' | 'interview' | 'offer' | 'rejected' | 'withdrawn';
        job_description?: string;
        salary_range?: string;
        location?: string;
        application_url?: string;
        contact_person?: string;
        contact_email?: string;
        interview_dates?: string[];
        follow_up_dates?: string[];
        notes?: string;
        skills_required?: string[];
        company_research?: string;
        application_materials?: string[];
        next_steps?: string;
        priority_level?: 'low' | 'medium' | 'high';
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        company_name?: string;
        position_title?: string;
        application_date?: string;
        application_status?: 'applied' | 'screening' | 'interview' | 'offer' | 'rejected' | 'withdrawn';
        job_description?: string;
        salary_range?: string;
        location?: string;
        application_url?: string;
        contact_person?: string;
        contact_email?: string;
        interview_dates?: string[];
        follow_up_dates?: string[];
        notes?: string;
        skills_required?: string[];
        company_research?: string;
        application_materials?: string[];
        next_steps?: string;
        priority_level?: 'low' | 'medium' | 'high';
        created_at?: string;
        updated_at?: string;
      };
    };
  };
};